name: greencart_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  auto_route: 9.3.0+1
  dio: 5.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: 2.6.1
  flutter_secure_storage: 9.2.4
  flutter_svg: 2.0.17
  freezed_annotation: 2.4.4
  iconsax_plus: 1.0.0
  intl: 0.20.1
  json_annotation: 4.9.0
  package_info_plus: 8.1.3
  retrofit: 4.4.2
  riverpod_annotation: 2.6.1
  sentry_dio: 8.12.0
  sentry_flutter: 8.12.0
  shared_preferences: 2.3.5
  skeletonizer: 1.4.3
  talker_dio_logger: 4.6.5
  talker_flutter: 4.6.5
  talker_riverpod_logger: 4.6.5
  toastification: 2.3.0
  url_launcher: 6.3.1

dev_dependencies:
  auto_route_generator: 9.3.1
  build_runner: 2.4.14
  custom_lint: 0.7.1
  flutter_gen_runner: 5.8.0
  flutter_launcher_icons: 0.14.3
  flutter_lints: 5.0.0
  flutter_native_splash: 2.4.4
  flutter_test:
    sdk: flutter
  freezed: 2.5.8
  json_serializable: 6.9.3
  retrofit_generator: 9.1.7
  riverpod_generator: 2.6.4
  riverpod_lint: 2.6.4
  sentry_dart_plugin: 2.3.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    # - assets/icons/

flutter_gen:
  output: lib/core/assets_gen
  assets:
    outputs:
      class_name: GreenCartAssets
      package_parameter_enabled: false
      directory_path_enabled: true

  integrations:
    flutter_svg: true

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  ios: true
  android: true
  # image_path_ios: "assets/common/app-icon.png"
  # image_path_ios_dark_transparent: "assets/common/app-icon-transparent.png"
  # image_path_android: "assets/android/app-icon.png"
  # adaptive_icon_foreground: "assets/android/app-icon-foreground.png"
  # adaptive_icon_background: "assets/android/app-icon-background.png"
  remove_alpha_ios: true
  web:
    generate: true
    # image_path: "assets/common/app-icon.png"

# Flutter Native Splash configuration
flutter_native_splash:
  color: "#ffffff"
  color_android: "#ffffff"
  color_dark_android: "#121212"
  color_ios: "#ffffff"
  color_dark_ios: "#121212"
  color_web: "#ffffff"
  color_dark_web: "#121212"
  # image: "assets/common/app-icon-transparent.png"

# Sentry Dart Plugin configuration
sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: true
  # project: 
  # org: 
  wait_for_processing: true
  log_level: error # possible values: trace, debug, info, warn, error
  commits: auto
  ignore_missing: true
  symbols_path: build
